// src/mapDelivery/layerTypes.js
// Shared layer delivery type constants for gradual Phase 2A migration.

export const LAYER_TYPES = Object.freeze({
  BASEMAP: "BASEMAP",
  CLIPPED_BASEMAP: "CLIPPED_BASEMAP",
  GEOSERVER_GWC_UNFILTERED: "GEOSERVER_GWC_UNFILTERED",
  GEOSERVER_WMS_FILTERED: "GEOSERVER_WMS_FILTERED",
  VECTOR_BOUNDARY: "VECTOR_BOUNDARY",
  WFS_DYNAMIC: "WFS_DYNAMIC",
  GET_FEATURE_INFO: "GET_FEATURE_INFO",
  USER_PRIVATE: "USER_PRIVATE",
});

export const TILE_PRIORITIES = Object.freeze({
  VISIBLE_SELECTED: 1,
  CURRENT_BASEMAP: 2,
  ACTIVE_OVERLAY: 3,
  CLICK_INFO: 4,
  NEARBY_PREFETCH: 5,
  IDLE_WARM: 6,
});
